In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [3]:
print(a[0], a[1], a[2])

1 2 3


In [5]:
a[0] = 5
print(a)

[5 2 3]


In [7]:
b = np.array([ [1, 2, 3], [4, 5, 6] ])
print(b.shape)
print(b)
print( b[0, 0], b[0, 1], b[1, 1])

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 5


In [8]:
#Numpy also provides many functions to create arrays

a = np.zeros( (2, 2))
print(a)

[[0. 0.]
 [0. 0.]]


In [9]:
b = np.ones( (1, 2) )
print(b)

[[1. 1.]]


In [10]:
c = np.full( (2, 3), 5)
print(c)

[[5 5 5]
 [5 5 5]]


In [11]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
e = np.random.random( (3, 3) )
print(e)

[[0.16874902 0.87621181 0.63065648]
 [0.51322886 0.15543343 0.52726835]
 [0.52461753 0.965952   0.26234371]]


In [15]:
# Array indexing

a = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

b = a[:2, 1:3] # rows 0~1 & columns 1~2
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [16]:
print( a[0, 1])

2


In [17]:
b[1, 1] = 5
print(b)

[[2 3]
 [6 5]]


*You can also mix **integer indexing** with slice indexing.
However, doing so will yield an array of lower rank than the original array.* 

In [18]:
a = np.array( [ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [23]:
#둘다 지칭하는 값은 같지만 출력 형태가 다름

row_r1 = a[1, :] #2nd row가 칼럼(벡터?) 형태로 저장됨
row_r2 = a[1:2, :] #2nd row가 row 형태로 저장됨

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [24]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Integer array indexing**: *When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original*

In [26]:
a = np.array( [ [1, 2], [3, 4], [5, 6] ] )

print(a)
print( a[ [0, 1, 2], [0, 1, 0] ] )  #???

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [27]:
print( np.array([ a[0, 0], a[1, 1], a[2, 0] ]) )  #위와 동일

[1 4 5]


In [28]:
print( a[ [0, 0], [1, 1]])  #???

[2 2]


In [29]:
print( np.array( [ a[0, 1], a[0, 1] ]))  #위와 동일

[2 2]


*One useful trick with integer array indexing is **selecting or mutating** one element from each row of a matrix*

In [30]:
a = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ])

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [32]:
b = np.array( [0, 2, 0, 1])

print(b, b.shape)

[0 2 0 1] (4,)


In [34]:
print( a[np.arange(4), b])

#각 row의 0, 2, 0, 1번째 값

[ 1  6  7 11]


In [35]:
a[np.arange(4), b] += 10

print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing**: *Boolean array indexing lets you pick out arbitrary elements of an array.*

In [36]:
a = np.array([ [1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [42]:
print( a[bool_idx] )

[3 4 5 6]


In [43]:
print( a[ a > 2])

[3 4 5 6]
